import type { Metadata } from "next";
import { Montserrat, Raleway } from "next/font/google";
import Providers from "@/components/Providers";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "700"],
  style: ["normal"],
  display: "swap",
  preload: true,
  variable: "--font-montserrat-family",
});

const raleway = Raleway({
  subsets: ["latin", "cyrillic"],
  weight: ["700"],
  style: ["normal"],
  display: "swap",
  preload: true,
  variable: "--font-raleway-family",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${montserrat.variable} ${raleway.variable} h-full antialiased`}
    >
      <body
        className={`${montserrat.className} min-h-full flex flex-col bg-dark-800`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
